### PR TITLE
improve the performance on mobile devices

### PR DESCRIPTION
**Pull request by DanielRuf**
On Chrome mobile the enter callback does not directly trigger and it seems it is very slow until it finally triggers the enter callback after waiting a few seconds.

I tested it with requestAnimationFrame and it was much better. I did not add the cancelAnimationFrame code as this is not used here. Did not test it on an old Android version as I have a new version with Chrome 58 and not the old webview for Android <= 4.4.4.

requestAnimationFrame shim from https://github.com/ConnorAtherton/walkway

rtimeOut code from https://codereview.stackexchange.com/questions/47889/alternative-to-setinterval-and-settimeout

### CODE REVIEW

**Comment by DanielRuf** [comment]
Will fix the errors right now, have to create a new environment.

**Comment by jeremenichelli** [comment]
@DanielRuf I wouldn't suggest either including a requestAnimationFrame shim or adding global functions that can be override but other script or deleted.

I want to keep the script as specific as possible with no overheads on other APIs.

That said, it's interesting to think that on old devices with a modern browser stack a `requestAnimationFrame` call might perform better than throttling the action by default.

I will build a local version with rAF and see if I notice a big difference and can come up with a cleaner solution with better performance.

**Comment by DanielRuf** [comment]
> old devices with a modern browser stack a requestAnimationFrame call might perform better than throttling the action by default.

Well, I use an Motorola G (3rd gen, 2015) with Android 7. Not really old. And yes this fixes it.

**Comment by jeremenichelli** [comment]
Hi @DanielRuf, sorry for the late response. I really like the requestAnimationFrame + time out approach. Though I would try to clean up the code a little bit to pass the lint rules and be more readable.

Also, it's not recommended to save the function in the `window` object, let me know if you can address this.

**Comment by DanielRuf** [comment]
> Also, it's not recommended to save the function in the window object, let me know if you can address this.

Which one? The code is taken from the shim and that's how they implemented it. Keep in mind that this is normally the way to add global namespaces and functions for the browser environment as in strict mode without this it might not work reliably.

The eslint errors were already fixed or which rules do you mean?

**Comment by jeremenichelli** [comment]
You are defining the `rtimeOut` function in the window object which is not recommendable since other libraries can reset it and break the code, it could be a function enclosed in the library itself since it gets wrapped in a IIFE.

About the linting rules, they passed becaused there are some eslint disable lines, ideally those rules should be addressed instead of being avoided.

**Comment by DanielRuf** [comment]
I've updated my branch and solved the merge conflicts.

**Comment by DanielRuf** [comment]
Wil fix the other issues too.

Quick question: does it make sense to also add the eventlistener for `orientationchange`?

**Comment by jeremenichelli** [comment]
@markgoodyear, Daniel has come up with a similar solution to you that also brings some performance improvements on the polling combining requestAnimationFrame with setTimeout. Would you mind testing this patch locally and see if this also addresses the issues present in your PR? Thanks.

**Comment by markgoodyear** [comment]
@jeremenichelli Sure I'll try look at this tomorrow, or Monday latest. When testing rAF myself I had no issues, but I didn't use it with a timeout, which is the part that causes the issue I had. Out of curiosity, is a timeout needed with rAF? Would the browser not "throttle" automatically? I don't know a lot about rAF.

**Comment by jeremenichelli** [comment]
@markgoodyear what rAF does is to queue the callback to next frame, but it doesn't care much if that next frame is already bloated.

I'm thinking this solution might be too complicated since rAF gives the callback a time tag which can be used to calculate if the frame has passed the 16ms, but we can think about that later.

**Comment by markgoodyear** [comment]
@jeremenichelli Just testing the rAF with timeout version, I run into the same issue unfortunately.

**Comment by DanielRuf** [comment]
Personally never had this issue on Google Chrome with hardware acceleration enabled by default.
If your solution works better we should take yours.

**Comment by markgoodyear** [comment]
@DanielRuf I think it's just a use case dependant thing where it's noticeable, because I lazy load content using Hunt, the observed element moves and it's possible to hit the observed element during the timeout, therefore the callback gets missed.

I've added a rAF version to my fork here: https://github.com/markgoodyear/hunt/tree/raf — this is without the timeouts, be interesting to see what you find most performant on the devices you have. I've tested all 3 on iOS 11 (iPhone 6s) and Android (some average Motorola) and all 3 implementations seem to have similar performance for me.

**Comment by jeremenichelli** [comment]
@DanielRuf the PR form Mark is not about performance as yours, so it's not an approach competition itself, Mark changes actually patches an edge case where hunt should fire but that is prevented by the throttling which I consider a bug indeed.

**Comment by jeremenichelli** [comment]
It would be good if we could test the rAF branch from @markgoodyear in Daniel's devices to see if we have one solution which solves both performance and correct throttling.

**Comment by jeremenichelli** [comment]
@markgoodyear from what I tested pure rAF ticking and I see a lot of missing frames while scrolling. For now I think that Mark's first approach is getting in while we explore better ticking.

**Comment by markgoodyear** [comment]
@jeremenichelli  Sure, this route makes sense. Fixes the issue, then can work in the performance related optimisations around it.

**Comment by jeremenichelli** [comment]
Hey Daniel, I'm closing this for now. But I want to thank you for taking the time on this and collaborating. Feel free to ping me if you want to re-open the discussion about this ❤️

**Pull request closed without merging**
