### PR TITLE
fix issue in Edge with svg elements

### PR DESCRIPTION
**Pull request by DanielRuf**
dataset is undefined / null in Edge when Hunt is used on (inline) svg elements.

### CODE REVIEW

**Comment by jeremenichelli** [comment]
Great catch @DanielRuf! Will review and merge this tonight, thanks!

**Comment by jeremenichelli** [comment]
If you can, do `npm run lint` and fix the errors, that might speed up publishing times.

**Comment by jeremenichelli** [comment]
@DanielRuf merged and published in `v3.0.1`, thanks again!

**Comment by DanielRuf** [comment]
Great, thanks =)

You are welcome!

**Pull request merged**
